// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project.Data;

#nullable disable

namespace Project.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240503164109_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("Project.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("StockId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StockId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTimeOffset(new DateTime(2024, 5, 3, 22, 41, 8, 372, DateTimeKind.Unspecified).AddTicks(5357), new TimeSpan(0, 6, 0, 0, 0)),
                            Description = "This is a great stock to invest in.",
                            StockId = 1,
                            Title = "Great stock"
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTimeOffset(new DateTime(2024, 5, 3, 22, 41, 8, 372, DateTimeKind.Unspecified).AddTicks(5362), new TimeSpan(0, 6, 0, 0, 0)),
                            Description = "I think this stock is overpriced.",
                            StockId = 2,
                            Title = "Overpriced"
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = new DateTimeOffset(new DateTime(2024, 5, 3, 22, 41, 8, 372, DateTimeKind.Unspecified).AddTicks(5366), new TimeSpan(0, 6, 0, 0, 0)),
                            Description = "This stock is undervalued.",
                            StockId = 3,
                            Title = "Undervalued"
                        },
                        new
                        {
                            Id = 4,
                            CreatedOn = new DateTimeOffset(new DateTime(2024, 5, 3, 22, 41, 8, 372, DateTimeKind.Unspecified).AddTicks(5371), new TimeSpan(0, 6, 0, 0, 0)),
                            Description = "Investing in this stock is high risk.",
                            StockId = 4,
                            Title = "High risk"
                        },
                        new
                        {
                            Id = 5,
                            CreatedOn = new DateTimeOffset(new DateTime(2024, 5, 3, 22, 41, 8, 372, DateTimeKind.Unspecified).AddTicks(5375), new TimeSpan(0, 6, 0, 0, 0)),
                            Description = "This stock pays a good dividend.",
                            StockId = 5,
                            Title = "Good dividend"
                        });
                });

            modelBuilder.Entity("Project.Models.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LastDividend")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<long>("MarketCapital")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Purchase")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Stocks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Company = "Apple Inc.",
                            Industry = "Technology",
                            LastDividend = 0.82m,
                            MarketCapital = 2000000000L,
                            Purchase = 150.00m,
                            Symbol = "AAPL"
                        },
                        new
                        {
                            Id = 2,
                            Company = "Alphabet Inc.",
                            Industry = "Technology",
                            LastDividend = 10.60m,
                            MarketCapital = 1800000000L,
                            Purchase = 2500.00m,
                            Symbol = "GOOGL"
                        },
                        new
                        {
                            Id = 3,
                            Company = "Microsoft Corporation",
                            Industry = "Technology",
                            LastDividend = 2.04m,
                            MarketCapital = 1600000000L,
                            Purchase = 300.00m,
                            Symbol = "MSFT"
                        },
                        new
                        {
                            Id = 4,
                            Company = "Amazon.com, Inc.",
                            Industry = "E-commerce",
                            LastDividend = 0m,
                            MarketCapital = 1700000000L,
                            Purchase = 3300.00m,
                            Symbol = "AMZN"
                        },
                        new
                        {
                            Id = 5,
                            Company = "Tesla, Inc.",
                            Industry = "Automotive",
                            LastDividend = 0m,
                            MarketCapital = 800000000L,
                            Purchase = 700.00m,
                            Symbol = "TSLA"
                        });
                });

            modelBuilder.Entity("Project.Models.Comment", b =>
                {
                    b.HasOne("Project.Models.Stock", "Stock")
                        .WithMany("Comments")
                        .HasForeignKey("StockId");

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("Project.Models.Stock", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
